apache2:
  build: apache2
  hostname: SITE_HOSTNAME
  restart: always
  ports:
    - "80:80"
  links:
    - exp
exp:
  build: exp
  restart: always
  ports:
    - "8080:8080"
  volumes_from:
    - "storage"
storage:
  build: storage
mail:
  image: enoniccloud/postfix
  hostname: SITE_HOSTNAME
  restart: always